### ISSUE TITLE
About release

### ISSUE THREAD

**Issue by TokyLapis** [mybabyyh/Preim3D#1]
really interesting work! And when will the code be released？

**Comment by mybabyyh** [comment]
> really interesting work! And when will the code be released？

Thank you for your interest, we will release the source code and pre-trained models in June.

**Comment by amandpkr** [comment]
Hi,

we are you planning to make the code public

**Comment by mybabyyh** [comment]
> Hi,
> 
> we are you planning to make the code public

We apologize that some work has interrupted our code release program. We aim to release the code as soon as possible.
